- README.md
When running `brew cask install secretive`, you get this error:
```shell
$ brew cask install secretive
Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
```
This PR updates the docs to use `brew install` instead of `brew cask install`
> brew cask install is deprecated

- Secretive/Views/CreateSecretView.swift
I was a little confused when I first created a secret.  This should make `requiresAuthentication` clearer to the user.
Fixes #209
> Changed checkbox to radio button for clearer UI.

- APP_CONFIG.md
Added setup instructions for the popular git client GitKraken. It's pretty much exactly the same as Cyberduck, with the added instruction of enabling "Use local SSH client" in GitKraken settings.
> Add setup instructions for GitKraken

- Sources/SecretAgent/Notifier.swift
Still haven't been able to get really long durations working reliably, so I'm removing the 24h option.
> Remove 24h unlock duration

- .github/workflows/nightly.yml
- .github/workflows/release.yml
This pull request adds a sha-256 checksum to the "Document SHAs" step of the build process to make it easier to verify that the checksum embedded in the [homebrew formula](https://github.com/Homebrew/homebrew-cask/blob/f616fe0cb0ff463480bd14213c7b9c65cf6c0a2e/Casks/secretive.rb) is the same as the checksum of the file built by GitHub Actions.
I've not actually been able to run this code in GitHub Actions (there are too many secrets to set up, as noted in #343) but the changes are simple enough that they should just work.
> Add sha-256 checksums to auditable build output

- FAQ.md
It happens so infrequently that I always forget and have to go looking for it, but every so often Secretive will stop working. As discussed [here](https://github.com/maxgoedjen/secretive/issues/363#issuecomment-1057863773) there is a Setup flow available in the Help menu that is undocumented, which solves the problem basically every time. This PR adds a line about it to the FAQ so that I (and anyone else with a similar problem) can find it and be reminded. Happy to rephrase or edit etc but I think this'll cut down on bug reports too!
> Add line about help/setup tool to FAQ

- Sources/Packages/Sources/SecretAgentKit/Agent.swift
This change adds initial OpenSSH certificate support and closes https://github.com/maxgoedjen/secretive/issues/269
If a a cert file exists for a public key in the 'PublicKeys' directory, SecretAgent will use it instead of the PublicKey. 
For example if Secretive creates a key with the path `~/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/PublicKeys/266b0718b08bc8653c885ae41534e1c0.pub` it will check if `~/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/PublicKeys/266b0718b08bc8653c885ae41534e1c0-cert.pub` exists, and return the contents as an available identity.
Upon a signing request it will attempt to check if the signing request is actually for a certificate, resolve it and sign using the correct secret instead.
This is probably pretty rough, im not a Swift …
> Initial openssh certificate support

- Sources/Packages/Sources/SecretAgentKit/Agent.swift
- Sources/Packages/Sources/SecretKit/Erasers/AnySecretStore.swift
- Sources/Packages/Sources/SecretKit/Types/SecretStore.swift
- Sources/Packages/Sources/SecureEnclaveSecretKit/SecureEnclaveStore.swift
- Sources/Packages/Sources/SmartCardSecretKit/SmartCardStore.swift
- Sources/Packages/Tests/SecretAgentKitTests/StubStore.swift
- Sources/Secretive/Preview Content/PreviewStore.swift
H/t @saagarjha for suggesting the root cause of this issue (basically, the agent being relaunched too early before the keychain has been unlocked).
I haven't been able to consistently reproduce the bug (either on VMs or real machines) – so this is a bit of a speculative fix.
Fixes #415
Fixes #426
Fixes #391 
Fixes #367
> Fix for SecretAgent acting as if it has no keys after updating macOS

- Sources/Secretive/Views/CopyableView.swift
> Tighten up light-scheme colors

- Sources/Packages/Sources/SecretKit/SecretStoreList.swift
- Sources/Secretive/Views/ContentView.swift
- Sources/Secretive/Views/DeleteSecretView.swift
- Sources/Secretive/Views/SecretListItemView.swift
- Sources/Secretive/Views/StoreListView.swift
> Fix bugs around selection after creating/deleting/updating keys

- Sources/Packages/Sources/SecretKit/Erasers/AnySecretStore.swift
- Sources/Packages/Sources/SecretKit/OpenSSH/OpenSSHKeyWriter.swift
- Sources/Packages/Sources/SecretKit/Types/Secret.swift
- Sources/Packages/Sources/SecretKit/Types/SecretStore.swift
- Sources/Packages/Sources/SecureEnclaveSecretKit/SecureEnclaveStore.swift
- Sources/Packages/Sources/SmartCardSecretKit/SmartCardStore.swift
- Sources/Packages/Tests/SecretAgentKitTests/AgentTests.swift
- Sources/Packages/Tests/SecretAgentKitTests/StubStore.swift
- Sources/Secretive/Preview Content/PreviewStore.swift
- Sources/Secretive/Views/EmptyStoreView.swift
I'm not sure who this is for, and I'm only 80% sure the openssh identifiers are correct, but you can do this, and you probably could support RSA keys on smart cards.
I could also probably move the verify and encrypt API up a few levels because it only needs a public key. 
Also, for completeness, the OpenSSH API should have a way to load the public keys.
> Rounded out the rest of the SmartCardStore API

- Sources/Secretive/Preview Content/PreviewStore.swift
Looks like these get cached aggressively.
> Fixed arg labels

- Sources/Packages/Sources/SecretAgentKit/Agent.swift
This PR modifies `Agent.identities()` to return certificates _in addition to_ keys, rather than returning only the certificate. This makes Secretive behave similarly to OpenSSH ssh-agent and addresses difficulties using the agent in scenarios where a private key can be used for authentication against a given remote server directly without the certificate.
Fixes #452.
> Identities offers both key and certificate when both are present

- Sources/Packages/Sources/SecretKit/PublicKeyStandinFileController.swift
The `try` on https://github.com/maxgoedjen/secretive/pull/476/files#diff-e73a4260fbc17590be26464100542cebbd891e5f21b5b068c275430d4ed6bb60L23 would throw if the directory had not yet been created, preventing the intended creation below.
Fixes #475
> Fix bug where public keys directory would not be created

- Sources/Packages/Sources/SecretAgentKit/Agent.swift
- Sources/Packages/Sources/SecretAgentKit/FileHandleProtocols.swift
- Sources/Packages/Sources/SecretAgentKit/SocketController.swift
- Sources/Packages/Sources/SecretKit/OpenSSH/OpenSSHCertificateHandler.swift
- Sources/Packages/Sources/SecretKit/PublicKeyStandinFileController.swift
- Sources/Packages/Tests/SecretAgentKitTests/AgentTests.swift
- Sources/SecretAgent/AppDelegate.swift
- Sources/Secretive/Controllers/LaunchAgentController.swift
Fixes #483
Fixes #392 
Also has some cleanup around loggers.
> Handle concurrent requests to socket

- Sources/Secretive/Localizable.xcstrings
This PR fixes the unintended display of `\n\n` in the "Agent is Running" popover:
> Fix escaped text on Agent is running popover

- Sources/SecretAgent/Localizable.xcstrings
- Sources/Secretive.xcodeproj/project.pbxproj
- Sources/Secretive/Localizable.xcstrings
Saw your proposal to write localization in the release notes and since I love using Secretive I did the one for French 🇫🇷!
I just had hesitation on how to translate the `agent_(not_)running_notice_title` because it's a bit inconsistent between using "Agent" (and click to see the details) and "Secret Agent":
- `agent_not_running_notice_title`: Secret Agent Is Not Running
- `agent_running_notice_title`: Agent is Running
So I translated that to the French common name with a determinant: "L'agent"
The rest should be fine!
> Add French localization

- .github/workflows/add-to-project.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
This PR updates some of this project's workflows to use newer versions of official reusable actions:
- [actions/add-to-project](https://github.com/actions/add-to-project) is updated to v1.0.1
- [actions/upload-artifact](https://github.com/actions/upload-artifact) is updated to v4
In both cases, the updates _should_ address deprecation notices on the changed workflows.
There are a few things I opted not to do as part of this PR:
**Fixing formatting and indentation in workflow YML files.** I ignored this for now as it would introduce a much larger diff and would obscure the meaningful changes.
**Migrating from archived actions to maintained replacements.** In 2021, GitHub archived two of the actions used by this project:
- [actions/create-release](https://github.com/actions/create-release) …
> GitHub Actions updates

- APP_CONFIG.md
This PR adds instructions for using Retcon with Secretive to the app config FAQ. These are simply a copy of VS Code instructions.
(right now, the [Retcon help](http://retcon.app/help) section about SSH clients links to VSC instructions, but it'll be nicer to link to a section named Retcon!)
> Add Retcon instructions to app config FAQ

- .github/workflows/nightly.yml
- .github/workflows/release.yml
Currently I prezip to prevent a weird situation where a GitHub zipped artifact will expand and just show the "Contents" directory of the `.app` – this is avoidable by uploading a folder containing the .app instead of the .app itself.
Fixes #730
> Zip parent directory to prevent double-zip/confusing attestation
