maxgoedjen/secretive

SecretAgentKit/Agent.swift
=> Fix padding bug

Secretive.xcodeproj/project.pbxproj, Secretive/AppDelegate.swift, Secretive/Controllers/JustUpdatedChecker.swift, Secretive/Controllers/LaunchAgentController.swift, Secretive/Views/SetupView.swift
=> Relaunch agent if updated

README.md
Update readme with Homebrew install instructions. :tada:
=> Add Homebrew install intructions

Brief/Updater.swift, BriefTests/BriefTests.swift, BriefTests/Info.plist, Config/Secretive.xctestplan, Secretive.xcodeproj/project.pbxproj
Fixes #144 
Well, that's why we write tests, isn't it.
=> Fix broken updater check

SecretAgent/Notifier.swift, SecretAgentKit/SigningRequestTracer.swift, SecretAgentKitTests/AgentTests.swift, SecretKit/Common/Types/SigningRequestProvenance.swift, SecretKit/SecureEnclave/SecureEnclaveStore.swift, SecretKit/SmartCard/SmartCardStore.swift
=> Tweak app name trace generation

APP_CONFIG.md, FAQ.md, Secretive/Views/SetupView.swift
=> Break out app faq

Secretive/App.swift, Secretive/Controllers/JustUpdatedChecker.swift, Secretive/Controllers/LaunchAgentController.swift, Secretive/Views/SetupView.swift
=> Fix issues around upgrading

SecretKit/Common/OpenSSH/OpenSSHKeyWriter.swift, Secretive/Views/SecretDetailView.swift
=> Add comment to public keys

SecretAgent/InternetAccessPolicy.plist, Secretive.xcodeproj/project.pbxproj, Secretive/InternetAccessPolicy.plist
=> Add internet access policy

SecretKit/Common/OpenSSH/OpenSSHKeyWriter.swift, SecretKitTests/OpenSSHWriterTests.swift, Secretive/Views/SecretDetailView.swift
=> Add support for SHA256 fingerprints

SecretKit/SecureEnclave/SecureEnclaveStore.swift, Secretive/Views/EmptyStoreView.swift
=> Fix arrow position

Secretive/Controllers/ShellConfigurationController.swift
=> Configure ssh directly instead of setting environment variable

CONTRIBUTING.md, Secretive/Credits.rtf
@0xflotus 
@joshheyse
Just FYI, if you'd rather have another name cited in the credits feel free to PR and I'll happily update them 🙏.
=> Add collabs to credits and update CONTRIBUTING.md

Secretive/Controllers/LaunchAgentController.swift
=> Fix focus resignation

.github/workflows/release.yml, .github/workflows/test.yml, Brief/Updater.swift, BriefTests/ReleaseParsingTests.swift, SecretAgentKitTests/StubStore.swift
=> Build with Xcode 13

Secretive/Views/SecretDetailView.swift
=> Embed Detail in ScrollView

SecretKit/SmartCard/SmartCardStore.swift
Holding until #224 is complete.
=> Add driver name when on macOS 12.0

.github/workflows/release.yml
=> Switch to Xcode 13 notarytool

Secretive.xcodeproj/project.pbxproj, Secretive/Controllers/ShellConfigurationController.swift, Secretive/Views/CreateSecretView.swift, Secretive/Views/DeleteSecretView.swift, Secretive/Views/RenameSecretView.swift, Secretive/Views/SetupView.swift
=> Enable additional concurrency warnings

.github/workflows/release.yml, .github/workflows/test.yml
=> Upload Xcode archive as release asset

.github/workflows/release.yml, Secretive.xcodeproj/project.pbxproj
Should make debugging/crash tracing a bit easier
=> Turn off stripping

Brief/Updater.swift, Secretive/App.swift, Secretive/Controllers/AgentStatusChecker.swift, Secretive/Preview Content/PreviewAgentStatusChecker.swift, Secretive/Preview Content/PreviewUpdater.swift, Secretive/Views/ContentView.swift
=> Quick prompting for stuff on debug/test builds

Sources/Packages/Sources/SecureEnclaveSecretKit/Documentation.docc/Documentation.md, Sources/Packages/Sources/SecureEnclaveSecretKit/SecureEnclave.swift, Sources/Packages/Sources/SecureEnclaveSecretKit/SecureEnclaveSecret.swift, Sources/Packages/Sources/SecureEnclaveSecretKit/SecureEnclaveStore.swift
=> Add docs for SecureEnclaveSecretKit

Sources/Packages/Sources/SmartCardSecretKit/Documentation.docc/Documentation.md, Sources/Packages/Sources/SmartCardSecretKit/SmartCard.swift, Sources/Packages/Sources/SmartCardSecretKit/SmartCardSecret.swift, Sources/Packages/Sources/SmartCardSecretKit/SmartCardStore.swift
=> Add docs for SmartCardSecretKit

Sources/Packages/Sources/Brief/Documentation.docc/Documentation.md, Sources/Packages/Sources/Brief/Release.swift, Sources/Packages/Sources/Brief/SemVer.swift, Sources/Packages/Sources/Brief/Updater.swift, Sources/Packages/Sources/Brief/UpdaterProtocol.swift, Sources/Packages/Sources/SecretAgentKit/Documentation.docc/Documentation.md, Sources/Packages/Sources/SecretKit/Documentation.docc/Documentation.md, Sources/Packages/Sources/SecureEnclaveSecretKit/Documentation.docc/Documentation.md, Sources/Packages/Sources/SmartCardSecretKit/Documentation.docc/Documentation.md
=> Break up Brief + Document

Sources/Packages/Sources/SecretAgentKit/SocketController.swift
SocketPort needs to be retained.
=> Unbreak socket controller

FAQ.md
Updated FAQ to link to the correct source for the updater.
=> Corrected FAQ link to Updater.swift source code

Sources/Secretive/Views/ContentView.swift
=> Fix presentation of setup view

.github/workflows/nightly.yml
=> Add nightly build

FAQ.md
=> Add uninstall FAQ entry.

Sources/SecretAgent/Notifier.swift
Reverts maxgoedjen/secretive#342
Fixes #345
=> Revert "Remove 24h unlock duration"

Sources/Packages/Sources/SecretKit/PublicKeyStandinFileController.swift
=> Switch key reps to an md5 based name

Sources/Packages/Sources/SecureEnclaveSecretKit/SecureEnclaveStore.swift
=> Specify immediate delivery

Sources/Packages/Sources/SecretKit/Types/SecretStore.swift, Sources/Packages/Sources/SecureEnclaveSecretKit/SecureEnclaveStore.swift, Sources/SecretAgent/AppDelegate.swift
Caused by the store not being reloaded before regeneration happened.
=> Fix bug where public key standins would not be regenerated

APP_CONFIG.md
Just duplicated configuration from Cyberduck
=> Mountain Duck shares SSH Agent configuration with Cyberduck

Sources/SecretAgent/Notifier.swift
=> Fix crash when tapping unlocked notification

Sources/Packages/Sources/SecretKit/PublicKeyStandinFileController.swift, Sources/Secretive/Views/SecretDetailView.swift
=> Don't delete public cert keys corresponding to Secretive-tracked keys

Sources/Packages/Sources/SecretAgentKit/SigningRequestTracer.swift
=> Fix crash on cstring init

FAQ.md, Sources/Secretive.xcodeproj/xcshareddata/xcschemes/Secretive.xcscheme, Sources/Secretive/Views/ContentView.swift, Sources/Secretive/Views/CreateSecretView.swift
=> Create Secret Screen Redesign

Sources/Secretive.xcodeproj/project.pbxproj, Sources/Secretive/Views/ContentView.swift, Sources/Secretive/Views/ToolbarButtonStyle.swift
=> Switch toolbar items to viewbuilders

Sources/Secretive/Views/ContentView.swift
=> Fix popovers not showing on Sonoma beta

Sources/Packages/Sources/SecretAgentKit/SigningRequestTracer.swift
=> Fix every request creating a duplicate icon in temporary directory

FAQ.md
I came here trying to figure out if I could generate an RSA key for some hardware that has still yet to release a firmware update supporting EC-key based authentication. It may help others. I didn't take smartcard support into consideration, so if that changes the answer, please modify it accordingly.
=> Add FAQ item for generating RSA keys

Sources/Secretive/Localizable.xcstrings
=> Translating_PR

Sources/Secretive/Localizable.xcstrings
=> Fix missing French translations

Sources/Secretive.xcodeproj/project.pbxproj, Sources/Secretive/Localizable.xcstrings
Adding Portuguese (Brazil) i18n to Secretive :-) 
Happy to collaborate with this great project
=> Add Portuguese (Brazil) Localization 🇧🇷

Sources/Secretive.xcodeproj/project.pbxproj, Sources/Secretive/Localizable.xcstrings
Thanks for making this awesome app! 🙌 
Translating technical terms like "secret" is always a bit tricky so kept this one as I think it makes sense for a technical tool like Secretive. Would be awesome if another native speaker could give some feedback!
=> Add German Localization 🇩🇪 

Sources/Secretive.xcodeproj/project.pbxproj, Sources/Secretive/Localizable.xcstrings
This PR adds a Finnish (`fi`) localization.
=> Add Finnish localization

.github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/test.yml
Turns out it's not free for open source 🤦
=> Revert "Use Apple Silicon runners"

Sources/Secretive/Localizable.xcstrings
**Problem**
There is no Japanese translations added yet.
**Solution**
Translate all strings in Japanese.
=> Add Japanese translations

Sources/Secretive.xcodeproj/project.pbxproj, Sources/Secretive/Localizable.xcstrings
Just pitching in with my small contribution to this project.
=> Add Russian localization

Sources/Secretive/Views/ContentView.swift, Sources/Secretive/Views/ToolbarButtonStyle.swift
Redesign toolbar items for Xcode 26.
=> macOS 26 Toolbar Styling

Sources/Packages/Sources/SecureEnclaveSecretKit/SecureEnclaveStore.swift
Doesn't _seem_ to be needed but...
=> Specify private key usage explicitly

Sources/Packages/Resources/Localizable.xcstrings
Some localization updates. 
I would rather have the history, signature and GitHub stats retained, hence I decided to opt for a pull request.
=> Update Russian localization

README.md
Clarified the description of key storage and access in Secretive.
=> Update readme for keychain notes

Sources/Secretive/App.swift, Sources/Secretive/Controllers/AgentStatusChecker.swift, Sources/Secretive/Views/Views/AgentStatusView.swift
=> Fix bug where agent could relaunch after being disabled
